// Indian food calorie reference.
// Each entry: name, aliases (lowercase words users might say/type), unit (default serving),
// kcal per one default serving, and optionally g (grams in one serving) so gram inputs can be scaled.
// Values are typical home-style estimates; restaurant portions are often richer.
export const FOODS = [
  // Breads
  { name: "Roti / Chapati", aliases: ["roti", "chapati", "chapatti", "phulka", "fulka", "rotis", "chapatis"], unit: "piece", kcal: 100, g: 40 },
  { name: "Butter roti", aliases: ["butter roti", "tawa butter roti"], unit: "piece", kcal: 135, g: 45 },
  { name: "Tandoori roti", aliases: ["tandoori roti"], unit: "piece", kcal: 120, g: 45 },
  { name: "Naan", aliases: ["naan", "nan"], unit: "piece", kcal: 260, g: 90 },
  { name: "Butter naan", aliases: ["butter naan"], unit: "piece", kcal: 310, g: 95 },
  { name: "Garlic naan", aliases: ["garlic naan"], unit: "piece", kcal: 300, g: 95 },
  { name: "Plain paratha", aliases: ["paratha", "parantha", "plain paratha", "lachha paratha"], unit: "piece", kcal: 200, g: 60 },
  { name: "Aloo paratha", aliases: ["aloo paratha", "alu paratha", "potato paratha"], unit: "piece", kcal: 290, g: 110 },
  { name: "Paneer paratha", aliases: ["paneer paratha"], unit: "piece", kcal: 320, g: 110 },
  { name: "Gobi paratha", aliases: ["gobi paratha", "gobhi paratha"], unit: "piece", kcal: 250, g: 110 },
  { name: "Methi thepla", aliases: ["thepla", "methi thepla"], unit: "piece", kcal: 120, g: 40 },
  { name: "Puri", aliases: ["puri", "poori", "puris", "pooris"], unit: "piece", kcal: 100, g: 25 },
  { name: "Bhatura", aliases: ["bhatura", "bhature", "bhaturas"], unit: "piece", kcal: 300, g: 80 },
  { name: "Missi roti", aliases: ["missi roti"], unit: "piece", kcal: 140, g: 50 },
  { name: "Makki di roti", aliases: ["makki roti", "makki di roti", "makki ki roti"], unit: "piece", kcal: 180, g: 60 },
  { name: "Bajra roti", aliases: ["bajra roti", "bajra rotla", "bhakri", "jowar roti", "jowar bhakri"], unit: "piece", kcal: 120, g: 45 },
  { name: "Bread slice", aliases: ["bread", "bread slice", "slice of bread", "toast", "brown bread"], unit: "slice", kcal: 75, g: 28 },
  { name: "Pav", aliases: ["pav", "pao", "bun"], unit: "piece", kcal: 120, g: 40 },

  // Rice
  { name: "Steamed rice", aliases: ["rice", "chawal", "plain rice", "steamed rice", "white rice", "boiled rice"], unit: "katori", kcal: 200, g: 150 },
  { name: "Brown rice", aliases: ["brown rice"], unit: "katori", kcal: 170, g: 150 },
  { name: "Jeera rice", aliases: ["jeera rice", "cumin rice"], unit: "katori", kcal: 250, g: 150 },
  { name: "Veg pulao", aliases: ["pulao", "pulav", "veg pulao", "vegetable pulao", "matar pulao"], unit: "katori", kcal: 270, g: 150 },
  { name: "Veg biryani", aliases: ["veg biryani", "vegetable biryani", "biryani"], unit: "plate", kcal: 450, g: 300 },
  { name: "Chicken biryani", aliases: ["chicken biryani"], unit: "plate", kcal: 600, g: 350 },
  { name: "Mutton biryani", aliases: ["mutton biryani", "gosht biryani"], unit: "plate", kcal: 700, g: 350 },
  { name: "Egg biryani", aliases: ["egg biryani", "anda biryani"], unit: "plate", kcal: 520, g: 320 },
  { name: "Khichdi", aliases: ["khichdi", "khichri", "dal khichdi"], unit: "katori", kcal: 210, g: 175 },
  { name: "Curd rice", aliases: ["curd rice", "dahi chawal", "thayir sadam"], unit: "katori", kcal: 230, g: 175 },
  { name: "Lemon rice", aliases: ["lemon rice", "chitranna"], unit: "katori", kcal: 250, g: 150 },
  { name: "Fried rice", aliases: ["fried rice", "veg fried rice"], unit: "plate", kcal: 420, g: 250 },
  { name: "Sambar rice", aliases: ["sambar rice", "sambar sadam", "bisi bele bath"], unit: "katori", kcal: 260, g: 200 },

  // Dals & curries
  { name: "Dal (plain / tadka)", aliases: ["dal", "daal", "dhal", "dal tadka", "tadka dal", "yellow dal", "moong dal", "toor dal", "arhar dal", "masoor dal", "lentils", "lentil"], unit: "katori", kcal: 150, g: 150 },
  { name: "Dal fry", aliases: ["dal fry"], unit: "katori", kcal: 180, g: 150 },
  { name: "Dal makhani", aliases: ["dal makhani", "dal makhni", "maa ki dal"], unit: "katori", kcal: 280, g: 150 },
  { name: "Rajma", aliases: ["rajma", "kidney beans", "rajma masala"], unit: "katori", kcal: 210, g: 150 },
  { name: "Chole", aliases: ["chole", "chhole", "chana masala", "chickpea curry", "chana", "chole masala"], unit: "katori", kcal: 230, g: 150 },
  { name: "Kadhi", aliases: ["kadhi", "kadi", "kadhi pakora"], unit: "katori", kcal: 190, g: 150 },
  { name: "Sambar", aliases: ["sambar", "sambhar"], unit: "katori", kcal: 130, g: 150 },
  { name: "Rasam", aliases: ["rasam"], unit: "katori", kcal: 60, g: 150 },
  { name: "Paneer butter masala", aliases: ["paneer butter masala", "paneer makhani", "butter paneer", "shahi paneer"], unit: "katori", kcal: 350, g: 150 },
  { name: "Palak paneer", aliases: ["palak paneer", "saag paneer"], unit: "katori", kcal: 260, g: 150 },
  { name: "Kadai paneer", aliases: ["kadai paneer", "kadhai paneer", "paneer masala", "paneer curry", "paneer sabzi"], unit: "katori", kcal: 300, g: 150 },
  { name: "Matar paneer", aliases: ["matar paneer", "mutter paneer"], unit: "katori", kcal: 270, g: 150 },
  { name: "Paneer bhurji", aliases: ["paneer bhurji"], unit: "katori", kcal: 280, g: 120 },
  { name: "Aloo sabzi", aliases: ["aloo sabzi", "aloo ki sabzi", "potato sabzi", "aloo fry", "jeera aloo", "aloo"], unit: "katori", kcal: 180, g: 150 },
  { name: "Aloo gobi", aliases: ["aloo gobi", "aloo gobhi", "gobi sabzi", "gobhi"], unit: "katori", kcal: 160, g: 150 },
  { name: "Aloo matar", aliases: ["aloo matar", "aloo mutter"], unit: "katori", kcal: 180, g: 150 },
  { name: "Bhindi masala", aliases: ["bhindi", "bhindi masala", "bhindi fry", "okra", "ladies finger"], unit: "katori", kcal: 150, g: 120 },
  { name: "Baingan bharta", aliases: ["baingan bharta", "baingan", "brinjal", "bharta", "eggplant"], unit: "katori", kcal: 140, g: 150 },
  { name: "Mixed veg sabzi", aliases: ["mix veg", "mixed veg", "mixed vegetable", "sabzi", "sabji", "vegetable curry", "veg curry", "subzi"], unit: "katori", kcal: 140, g: 150 },
  { name: "Lauki sabzi", aliases: ["lauki", "lauki sabzi", "ghiya", "bottle gourd", "tinda", "turai", "tori"], unit: "katori", kcal: 90, g: 150 },
  { name: "Cabbage sabzi", aliases: ["cabbage", "patta gobi", "band gobi", "cabbage sabzi", "poriyal", "thoran"], unit: "katori", kcal: 100, g: 150 },
  { name: "Palak / saag", aliases: ["palak", "saag", "sarson ka saag", "spinach"], unit: "katori", kcal: 140, g: 150 },
  { name: "Malai kofta", aliases: ["malai kofta", "kofta"], unit: "katori", kcal: 380, g: 150 },
  { name: "Butter chicken", aliases: ["butter chicken", "murgh makhani", "chicken makhani"], unit: "katori", kcal: 400, g: 150 },
  { name: "Chicken curry", aliases: ["chicken curry", "chicken", "chicken masala", "chicken gravy", "kadai chicken"], unit: "katori", kcal: 300, g: 150 },
  { name: "Chicken tikka", aliases: ["chicken tikka", "tandoori chicken", "tikka"], unit: "piece", kcal: 50, g: 30 },
  { name: "Chicken tikka masala", aliases: ["chicken tikka masala"], unit: "katori", kcal: 380, g: 150 },
  { name: "Mutton curry", aliases: ["mutton curry", "mutton", "rogan josh", "gosht", "lamb curry"], unit: "katori", kcal: 380, g: 150 },
  { name: "Fish curry", aliases: ["fish curry", "fish", "machli", "meen curry"], unit: "katori", kcal: 250, g: 150 },
  { name: "Fish fry", aliases: ["fish fry", "fried fish"], unit: "piece", kcal: 220, g: 100 },
  { name: "Egg curry", aliases: ["egg curry", "anda curry"], unit: "katori", kcal: 260, g: 150 },
  { name: "Keema", aliases: ["keema", "kheema", "mutton keema", "chicken keema"], unit: "katori", kcal: 350, g: 150 },

  // Eggs, dairy
  { name: "Boiled egg", aliases: ["egg", "eggs", "boiled egg", "boiled eggs", "anda", "ande"], unit: "piece", kcal: 75, g: 50 },
  { name: "Omelette", aliases: ["omelette", "omelet", "masala omelette", "anda omelette"], unit: "piece", kcal: 160, g: 100 },
  { name: "Egg bhurji", aliases: ["egg bhurji", "anda bhurji", "scrambled egg", "scrambled eggs"], unit: "katori", kcal: 220, g: 120 },
  { name: "Curd / Dahi", aliases: ["curd", "dahi", "yogurt", "yoghurt", "plain curd"], unit: "katori", kcal: 100, g: 150 },
  { name: "Raita", aliases: ["raita", "boondi raita", "cucumber raita"], unit: "katori", kcal: 110, g: 150 },
  { name: "Paneer (raw)", aliases: ["paneer", "cottage cheese"], unit: "g", kcal: 2.65, g: 1 },
  { name: "Milk", aliases: ["milk", "doodh", "glass of milk"], unit: "glass", kcal: 150, g: 250 },
  { name: "Lassi (sweet)", aliases: ["lassi", "sweet lassi", "mango lassi"], unit: "glass", kcal: 260, g: 250 },
  { name: "Chaas / Buttermilk", aliases: ["chaas", "chhach", "buttermilk", "mattha", "majjige", "neer mor"], unit: "glass", kcal: 45, g: 250 },
  { name: "Ghee", aliases: ["ghee"], unit: "tsp", kcal: 45, g: 5 },
  { name: "Butter", aliases: ["butter", "makhan"], unit: "tsp", kcal: 36, g: 5 },
  { name: "Cheese slice", aliases: ["cheese", "cheese slice"], unit: "slice", kcal: 65, g: 20 },

  // South Indian
  { name: "Idli", aliases: ["idli", "idly", "idlis", "idlies"], unit: "piece", kcal: 60, g: 40 },
  { name: "Plain dosa", aliases: ["dosa", "plain dosa", "sada dosa", "dosai"], unit: "piece", kcal: 170, g: 90 },
  { name: "Masala dosa", aliases: ["masala dosa"], unit: "piece", kcal: 380, g: 180 },
  { name: "Rava dosa", aliases: ["rava dosa"], unit: "piece", kcal: 210, g: 100 },
  { name: "Uttapam", aliases: ["uttapam", "uthappam", "onion uttapam"], unit: "piece", kcal: 220, g: 120 },
  { name: "Medu vada", aliases: ["vada", "medu vada", "vadai", "wada"], unit: "piece", kcal: 140, g: 45 },
  { name: "Upma", aliases: ["upma", "uppittu", "rava upma"], unit: "katori", kcal: 230, g: 150 },
  { name: "Pongal", aliases: ["pongal", "ven pongal"], unit: "katori", kcal: 260, g: 150 },
  { name: "Appam", aliases: ["appam"], unit: "piece", kcal: 120, g: 60 },
  { name: "Coconut chutney", aliases: ["chutney", "coconut chutney", "nariyal chutney"], unit: "tbsp", kcal: 35, g: 15 },
  { name: "Green chutney", aliases: ["green chutney", "pudina chutney", "mint chutney", "dhaniya chutney"], unit: "tbsp", kcal: 10, g: 15 },

  // Breakfast & snacks
  { name: "Poha", aliases: ["poha", "pohe", "kanda poha", "aval"], unit: "katori", kcal: 250, g: 150 },
  { name: "Dhokla", aliases: ["dhokla", "khaman", "khaman dhokla"], unit: "piece", kcal: 55, g: 30 },
  { name: "Besan chilla", aliases: ["chilla", "cheela", "besan chilla", "moong chilla", "pudla"], unit: "piece", kcal: 150, g: 70 },
  { name: "Samosa", aliases: ["samosa", "samosas"], unit: "piece", kcal: 260, g: 80 },
  { name: "Kachori", aliases: ["kachori", "kachoris"], unit: "piece", kcal: 190, g: 50 },
  { name: "Pakora / Bhajji", aliases: ["pakora", "pakoda", "pakode", "pakoras", "bhaji", "bhajji", "bajji", "onion pakoda"], unit: "piece", kcal: 50, g: 20 },
  { name: "Vada pav", aliases: ["vada pav", "vada pao", "wada pav"], unit: "piece", kcal: 300, g: 130 },
  { name: "Pav bhaji", aliases: ["pav bhaji", "pao bhaji"], unit: "plate", kcal: 450, g: 300 },
  { name: "Misal pav", aliases: ["misal", "misal pav"], unit: "plate", kcal: 480, g: 300 },
  { name: "Chole bhature", aliases: ["chole bhature", "chhole bhature"], unit: "plate", kcal: 750, g: 350 },
  { name: "Pani puri", aliases: ["pani puri", "golgappa", "gol gappa", "puchka", "golgappe"], unit: "piece", kcal: 35, g: 15 },
  { name: "Bhel puri", aliases: ["bhel", "bhel puri", "jhal muri"], unit: "plate", kcal: 250, g: 120 },
  { name: "Sev puri", aliases: ["sev puri", "dahi puri", "papdi chaat", "chaat"], unit: "plate", kcal: 300, g: 150 },
  { name: "Aloo tikki", aliases: ["aloo tikki", "tikki"], unit: "piece", kcal: 150, g: 60 },
  { name: "Momos (steamed)", aliases: ["momo", "momos", "steamed momos", "veg momos", "chicken momos"], unit: "piece", kcal: 40, g: 25 },
  { name: "Maggi / instant noodles", aliases: ["maggi", "noodles", "instant noodles"], unit: "packet", kcal: 350, g: 70 },
  { name: "Sandwich (veg)", aliases: ["sandwich", "veg sandwich", "grilled sandwich", "bombay sandwich"], unit: "piece", kcal: 250, g: 150 },
  { name: "Namkeen / mixture", aliases: ["namkeen", "mixture", "bhujia", "chivda", "farsan"], unit: "katori", kcal: 250, g: 50 },
  { name: "Biscuit", aliases: ["biscuit", "biscuits", "marie", "cookie", "cookies", "parle g"], unit: "piece", kcal: 35, g: 8 },
  { name: "Rusk", aliases: ["rusk", "toast rusk"], unit: "piece", kcal: 50, g: 12 },
  { name: "Roasted chana", aliases: ["roasted chana", "bhuna chana", "chana jor"], unit: "katori", kcal: 180, g: 50 },
  { name: "Makhana (roasted)", aliases: ["makhana", "fox nuts", "phool makhana"], unit: "katori", kcal: 100, g: 25 },
  { name: "Sprouts salad", aliases: ["sprouts", "moong sprouts", "sprout salad"], unit: "katori", kcal: 110, g: 100 },
  { name: "Green salad", aliases: ["salad", "green salad", "kachumber", "cucumber"], unit: "katori", kcal: 30, g: 100 },
  { name: "Papad", aliases: ["papad", "papadum", "appalam"], unit: "piece", kcal: 50, g: 12 },
  { name: "Pickle", aliases: ["pickle", "achar", "achaar"], unit: "tbsp", kcal: 40, g: 15 },

  // Sweets
  { name: "Gulab jamun", aliases: ["gulab jamun", "gulab jamuns", "jamun"], unit: "piece", kcal: 150, g: 40 },
  { name: "Rasgulla", aliases: ["rasgulla", "rasagola", "rosogolla"], unit: "piece", kcal: 120, g: 40 },
  { name: "Jalebi", aliases: ["jalebi", "jalebis"], unit: "piece", kcal: 150, g: 35 },
  { name: "Ladoo", aliases: ["ladoo", "laddu", "laddoo", "besan ladoo", "motichoor ladoo", "boondi ladoo"], unit: "piece", kcal: 180, g: 40 },
  { name: "Barfi / Kaju katli", aliases: ["barfi", "burfi", "kaju katli", "kaju barfi"], unit: "piece", kcal: 120, g: 25 },
  { name: "Kheer", aliases: ["kheer", "payasam", "rice kheer"], unit: "katori", kcal: 250, g: 150 },
  { name: "Halwa", aliases: ["halwa", "sooji halwa", "gajar halwa", "sheera", "kesari"], unit: "katori", kcal: 350, g: 120 },
  { name: "Rasmalai", aliases: ["rasmalai", "ras malai"], unit: "piece", kcal: 180, g: 60 },
  { name: "Ice cream", aliases: ["ice cream", "icecream", "kulfi"], unit: "scoop", kcal: 140, g: 65 },
  { name: "Sugar", aliases: ["sugar", "cheeni", "shakkar"], unit: "tsp", kcal: 20, g: 5 },
  { name: "Jaggery", aliases: ["jaggery", "gur", "gud"], unit: "piece", kcal: 40, g: 10 },
  { name: "Chocolate", aliases: ["chocolate", "dairy milk", "choco"], unit: "piece", kcal: 55, g: 10 },

  // Drinks
  { name: "Tea with milk & sugar", aliases: ["chai", "tea", "masala chai", "milk tea", "cutting chai", "cutting"], unit: "cup", kcal: 90, g: 150 },
  { name: "Black tea / green tea", aliases: ["green tea", "black tea", "lemon tea"], unit: "cup", kcal: 5, g: 150 },
  { name: "Coffee with milk & sugar", aliases: ["coffee", "filter coffee", "milk coffee", "cold coffee", "cappuccino", "latte"], unit: "cup", kcal: 110, g: 150 },
  { name: "Black coffee", aliases: ["black coffee", "americano", "espresso"], unit: "cup", kcal: 5, g: 150 },
  { name: "Nimbu pani", aliases: ["nimbu pani", "lemonade", "shikanji", "lemon water"], unit: "glass", kcal: 80, g: 250 },
  { name: "Coconut water", aliases: ["coconut water", "nariyal pani", "tender coconut"], unit: "glass", kcal: 45, g: 250 },
  { name: "Fresh juice", aliases: ["juice", "orange juice", "mosambi juice", "sugarcane juice", "fruit juice"], unit: "glass", kcal: 120, g: 250 },
  { name: "Soft drink", aliases: ["coke", "pepsi", "soft drink", "cola", "sprite", "thums up", "cold drink"], unit: "can", kcal: 140, g: 330 },
  { name: "Beer", aliases: ["beer"], unit: "glass", kcal: 150, g: 330 },

  // Fruits & nuts
  { name: "Banana", aliases: ["banana", "bananas", "kela"], unit: "piece", kcal: 105, g: 120 },
  { name: "Apple", aliases: ["apple", "apples", "seb"], unit: "piece", kcal: 95, g: 180 },
  { name: "Mango", aliases: ["mango", "mangoes", "aam"], unit: "piece", kcal: 200, g: 300 },
  { name: "Orange", aliases: ["orange", "oranges", "santra", "mosambi"], unit: "piece", kcal: 60, g: 130 },
  { name: "Papaya", aliases: ["papaya", "papita"], unit: "katori", kcal: 60, g: 150 },
  { name: "Guava", aliases: ["guava", "amrood"], unit: "piece", kcal: 70, g: 120 },
  { name: "Grapes", aliases: ["grapes", "angoor"], unit: "katori", kcal: 100, g: 150 },
  { name: "Watermelon", aliases: ["watermelon", "tarbooz"], unit: "katori", kcal: 45, g: 150 },
  { name: "Pomegranate", aliases: ["pomegranate", "anar"], unit: "katori", kcal: 120, g: 150 },
  { name: "Chikoo", aliases: ["chikoo", "chiku", "sapota"], unit: "piece", kcal: 80, g: 100 },
  { name: "Fruit bowl", aliases: ["fruits", "fruit", "fruit salad", "fruit bowl"], unit: "katori", kcal: 90, g: 150 },
  { name: "Almonds", aliases: ["almond", "almonds", "badam"], unit: "piece", kcal: 7, g: 1.2 },
  { name: "Cashews", aliases: ["cashew", "cashews", "kaju"], unit: "piece", kcal: 9, g: 1.6 },
  { name: "Walnut", aliases: ["walnut", "walnuts", "akhrot"], unit: "piece", kcal: 26, g: 4 },
  { name: "Peanuts", aliases: ["peanut", "peanuts", "moongphali", "groundnut", "groundnuts"], unit: "katori", kcal: 290, g: 50 },
  { name: "Dates", aliases: ["date", "dates", "khajoor"], unit: "piece", kcal: 23, g: 8 },
  { name: "Oats", aliases: ["oats", "oatmeal", "porridge", "daliya", "dalia"], unit: "katori", kcal: 160, g: 175 },
  { name: "Cornflakes with milk", aliases: ["cornflakes", "corn flakes", "cereal", "muesli"], unit: "katori", kcal: 200, g: 200 },
];

// Volumes (ml) used to convert between bowl-type units.
export const VOLUME_ML = { katori: 150, bowl: 250, cup: 150, glass: 250, plate: 300, tbsp: 15, tsp: 5, scoop: 65, can: 330, ml: 1 };
